#declare use_radiosity=2; // 1st pass: 2 / final: 1
#declare use_area     =0; // 1st pass: 0 / final: 1
#declare use_blur     =0; // 1st pass: 0 / final: >50 at least
#declare use_textures =0; // 1st pass: 0 / final: 1
#declare use_normals  =0; // 1st pass: 0 / final: 1
#declare use_glass    =0; // 1st pass: 0 / final: 1
#declare use_wshaders =0; // 1st pass: 0 / final: 1
#declare use_photons  =0; // 1st pass: 0 / final: 1

