#declare use_radiosity=1; // 1st pass: 2 / final: 1
#declare use_area     =1; // 1st pass: 0 / final: 1
#declare use_blur     =80; // 1st pass: 0 / final: >50 at least
#declare use_textures =1; // 1st pass: 0 / final: 1
#declare use_normals  =1; // 1st pass: 0 / final: 1
#declare use_glass    =0; // 1st pass: 0 / final: 1
#declare use_wshaders =1; // 1st pass: 0 / final: 1
#declare use_photons  =1; // 1st pass: 0 / final: 1

